// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterPasswordismorethan6andlessthan20charactersTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\DKayr\\OneDrive\\Masaüstü\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerPasswordismorethan6andlessthan20characters() {
    driver.get("https://www.kaft.com/");
    driver.manage().window().setSize(new Dimension(1440, 912));
    driver.findElement(By.linkText("Giriş")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.linkText("Üye Ol")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.id("customer.firstName")).click();
    driver.findElement(By.id("customer.firstName")).sendKeys("Ad");
    driver.findElement(By.id("customer.lastName")).click();
    driver.findElement(By.id("customer.lastName")).sendKeys("Soyad");
    driver.findElement(By.id("customer.emailAddress")).click();
    driver.findElement(By.id("customer.emailAddress")).sendKeys("Deneme64@hotmail.com");
    driver.findElement(By.id("password")).sendKeys("1234567890");
    driver.findElement(By.id("passwordConfirm")).sendKeys("1234567890");
    WebElement element =  driver.findElement(By.id("registerPolicy"));
    js.executeScript("arguments[0].click();",element);
    element = driver.findElement(By.id("submit-register-form"));
    js.executeScript("arguments[0].click();",element);
    assertTrue(driver.getPageSource().contains("Tebrikler"));

  }
}
